### ISSUE TITLE
Issue running from python Server 2008 R2 64

### ISSUE THREAD

**Issue by mcolson1985** [cisagov/CHIRP#21] opened 2021-03-22 18:58 UTC
# 🐛 Summary #
Issue running Python command on Server 2008 R2

see picture that error shows when tried to run chirp.exe app crash 

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.
![issue](https://user-images.githubusercontent.com/65629631/112042803-536f1280-8b1e-11eb-9d98-b9f83eb9e2c6.JPG)

second method running chirp.exe from powershell or CMD with administrator rights:
![chirpapp](https://user-images.githubusercontent.com/65629631/112043462-15262300-8b1f-11eb-801d-99a0a79886b1.JPG)

**Comment by DeemOnSecurity** [comment] 2021-03-22 19:30
This is a duplicate of #4. To run chirp with python, the dependencies must be installed. Instructions to do this are in the README.md file.

**Closed as completed by DeemOnSecurity** 2021-03-22 19:30 UTC
Labels: duplicate
