### ISSUE TITLE
[EVENTS] Read 0 logs, found 0 matches

### ISSUE THREAD

**Issue by rsmith16384** [cisagov/CHIRP#13] opened 2021-03-19 16:50 UTC
# 🐛 Summary #

From CLI output, I see this line:

[09:33:29] [EVENTS] Read 0 logs, found 0 matches.                                                         common.py:103

## To reproduce ##

1. Run Executable as administrator
2. Observe output

## Expected behavior ##

[09:33:29] [EVENTS] Read NNNN logs, found x matches.                                                         common.py:103

## Any helpful log output or screenshots ##

Paste the results here:

[09:30:18] [YARA] Enumerating the entire filesystem due to ['CISA Solar Fire', 'CISA Teardrop',           common.py:103
           'CrowdStrike Rempack', 'CrowdStrike Sunspot', 'FireEye Cosmic Gale', 'FireEye Sunburst']...
           this is going to take a while.
           [YARA] Entered yara plugin.                                                                    common.py:103
           [REGISTRY] Found 0 hit(s) for IFEO Persistence indicator.                                      common.py:103
           [REGISTRY] Found 0 hit(s) for Teardrop - Registry Activity indicator.                          common.py:103
           [REGISTRY] Found 0 hit(s) for Sibot - Registry indicator.                                      common.py:103
           [REGISTRY] Reading HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Image File    common.py:103
           Execution Options\
           [REGISTRY] Reading HKEY_LOCAL_MACHINE\Software\Microsoft\CTF                                   common.py:103
           [REGISTRY] Key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\sibot does not     common.py:103
           exist.
           [REGISTRY] Reading HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\sibot          common.py:103
           [REGISTRY] Entered registry plugin.                                                            common.py:103
           [NETWORK] Read 327 records, found 0 IoC hits.                                                  common.py:103
           [NETWORK] Entered network plugin.                                                              common.py:103
           [EVENTS] Entered events plugin.                                                                common.py:103
[09:30:36] [EVENTS] Reading KernelMode event logs.                                                        common.py:103
           [EVENTS] Reading Security event logs.                                                          common.py:103
           [EVENTS] Reading Windows Powershell event logs.                                                common.py:103
[09:33:27] [YARA] Beginning processing.                                                                   common.py:103
[09:33:29] [EVENTS] Read 0 logs, found 0 matches.                                                         common.py:103
[09:34:23] [YARA] We're still working on scanning files. 50000 processed.                                 common.py:103
[09:35:17] [YARA] We're still working on scanning files. 100000 processed.                                common.py:103
[09:36:17] [YARA] We're still working on scanning files. 150000 processed.                                common.py:103
[09:36:43] [YARA] We're still working on scanning files. 200000 processed.                                common.py:103
[09:37:29] [YARA] We're still working on scanning files. 250000 processed.                                common.py:103
[09:38:07] [YARA] We're still working on scanning files. 300000 processed.                                common.py:103
[09:38:39] [YARA] We're still working on scanning files. 350000 processed.                                common.py:103
[09:39:27] [YARA] We're still working on scanning files. 400000 processed.                                common.py:103
[09:39:51] [YARA] We're still working on scanning files. 450000 processed.                                common.py:103
[09:40:17] [YARA] We're still working on scanning files. 500000 processed.                                common.py:103
[09:40:41] [YARA] We're still working on scanning files. 550000 processed.                                common.py:103
[09:41:13] [YARA] We're still working on scanning files. 600000 processed.                                common.py:103
[09:42:07] [YARA] We're still working on scanning files. 650000 processed.                                common.py:103
[09:42:47] [YARA] We're still working on scanning files. 700000 processed.                                common.py:103
[09:43:15] [YARA] We're still working on scanning files. 750000 processed.                                common.py:103
[09:43:45] [+] DONE! Your results can be found in C:\ARTemp
![issue](https://user-images.githubusercontent.com/37616409/111814974-5a84ef00-8898-11eb-9a00-1753e43f48d5.png)
\chirp\output.                                 common.py:103
           [YARA] Found 0 hit(s) for yara indicators.                                                     common.py:103
           [YARA] Done. Processed 796957 files.                                                           common.py:103

Add any screenshots of the problem here.

**Comment by DeemOnSecurity** [comment] 2021-03-19 17:59
Interesting, can you verify the program isn't being blocked by antivirus? The processing speed for yara is significantly faster than I would expect, which makes me suspect it's being blocked from reading files.

**Comment by greyl0cke** [comment] 2021-03-20 18:20
I can confirm this issue exists with 1.0.2b with Windows Defender disabled.  Even if the folder or executable itself is excluded, it still reports 'Read 0 logs, found 0 matches'.
I even extracted and ran the tool from C:\Windows\system32\Winevt\Logs directory just to see if it was something with the file location.
![image](https://user-images.githubusercontent.com/59586489/111881586-69969a80-8987-11eb-83ee-31f02831df00.png)

**Comment by DeemOnSecurity** [comment] 2021-03-20 20:16
Interesting. What is the Windows version you are running? I’m going to try to replicate this in our dev environment.

**Comment by greyl0cke** [comment] 2021-03-20 20:22
> 
> 
> Interesting. What is the Windows version you are running? I’m going to try to replicate this in our dev environment.

Two machines I've tried on result in the same issue.  Both versions are below, let me know if you need anything else.
![image](https://user-images.githubusercontent.com/59586489/111884503-68ba3480-8998-11eb-9887-abf224c89f3c.png)
![image](https://user-images.githubusercontent.com/59586489/111884512-766fba00-8998-11eb-8c0e-0fe782abd962.png)

**Comment by rsmith16384** [comment] 2021-03-23 14:04
Same status with AV disabled

I tried running latest code using python, it now identifies that logs were not found in the default location, but output is a bit garbled and scan never completes (thats the last thing it tells me), any idea when there will be a new binary available to try out?
![noAV](https://user-images.githubusercontent.com/37616409/112159007-ef902c80-8ba5-11eb-9c16-693d454685b1.png)
![noAVscan](https://user-images.githubusercontent.com/37616409/112159029-f3bc4a00-8ba5-11eb-9bfa-e30bd13bf7e8.png)
![winver2](https://user-images.githubusercontent.com/37616409/112161099-0899dd00-8ba8-11eb-90ae-de435bd41f88.png)

**Comment by rsmith16384** [comment] 2021-03-24 16:20
Tried v1.0.3 release, same result

[09:17:09] [EVENTS] Read 0 logs, found 0 matches.

**Comment by greyl0cke** [comment] 2021-03-24 20:23
> 
> 
> Tried v1.0.3 release, same result
> 
> [09:17:09] [EVENTS] Read 0 logs, found 0 matches.

confirmed here as well.

**Comment by rsmith16384** [comment] 2021-03-30 14:31
Tested on Windows Server 2016 Standard version 1607 / OS Build 14393.4283

Same result

**Comment by DeemOnSecurity** [comment] 2021-03-30 19:26
Awesome, I am now seeing this error with the GitHub CI-built binary as well but not with the locally built binary. Once we discern the difference I reckon we will squash this bug.

**Comment by DeemOnSecurity** [comment] 2021-03-31 02:31
This and #4 may be related in that our CI rules are not setting up the environment correctly for compilation. I plan on attempting to patch this on Thursday. 

Current thoughts:
- Python 3.9.5 (as we're using the new version) is causing #4, since it is not technically compatible
- Mingw64 and possibly not setting up a virtual env prior to compilation is causing this issue, should consider compiling with the most recent stable version of msvc.

**Comment by DeemOnSecurity** [comment] 2021-04-01 17:52
Unintentionally closed by `Fix` magic word in commit message.

**Comment by DeemOnSecurity** [comment] 2021-04-01 17:53
@rsmith16384 @greyl0cke This should be fixed with #30, would appreciate a run on your end before I close the issue.

**Comment by rsmith16384** [comment] 2021-04-01 19:32
Here is screenshot from Windows Server 2016 Standard version 1607 / OS Build 14393.4283, now reading logs, great work!

![squashed](https://user-images.githubusercontent.com/37616409/113344418-e7db3100-92e5-11eb-9123-01fb47c8a705.png)

**Comment by DeemOnSecurity** [comment] 2021-04-01 19:45
Awesome! Happy to resolve this!

**Closed as completed by DeemOnSecurity** 2021-04-01 19:45 UTC
Labels: bug
